services:
  - type: web
    name: QRcode_generator_API
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn QRcode_generator_API.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key : ALLOWED_HOSTS
        value : ['.onreder.com']
      - key : SECRET_KEY
        generateValue : true
